Create event by clicking on calendar
u2i/confy pull request #140
Opened 2016-09-13 11:39 UTC by lkudyba

@quirk0o @mhib @jtkpiotr @adamzima @s1mplex

2016-09-13 13:53 UTC, quirk0o commented on client/app/components/calendar/CalendarContainer.jsx
> +  handleAddClick(startTime, endTime) {
Why not handleClick?

2016-09-15 07:30 UTC, mhib approved these changes
2/10

2016-09-19 13:32 UTC, adamzima commented
No specs :(?

2016-09-21 07:49 UTC, madejejej requested changes

2016-09-21 07:49 UTC, madejejej commented on client/app/components/calendar/CalendarContainer.jsx
> +    if (this.modal) {
Why do you have to check for `modal` presence after opening it?

2016-09-21 07:49 UTC, madejejej commented on client/app/components/calendar/event/EventWrapper.jsx
> +    this._handleCellClick = this._handleCellClick.bind(this);
How about refactoring these calls using `bindAll`?

2016-09-21 09:26 UTC, madejejej approved these changes

2016-09-22 08:27 UTC, merged