Datepicker
u2i/confy pull request #145
Opened 2016-09-15 13:12 UTC by quirk0o

@adamzima @s1mplex @lkudyba @jtkpiotr

2016-09-15 15:07 UTC, adamzima commented on client/.eslintrc.yml
> +  jquery: true
:(

2016-09-19 10:03 UTC, s1mplex commented on client/app/helpers/DateHelper.js
> +  if (diff > 60) {
I don't get the magic number 60 here. There's a test case called "with time almost equal to a multiple of granularity" that covers this. Why are you not using a value like `granularity / 2` instead? If this is intended then I think extracting 60 to a well-named constant would clarify a lot.

2016-09-19 10:06 UTC, madejejej approved these changes

2016-09-19 10:06 UTC, madejejej commented on client/app/components/shared/time/datepicker/TimeInput.jsx
> +             className={`time form-control ${this.props.className}`}
Do you need `{}` brackets here?

2016-09-20 09:50 UTC, jtkpiotr commented on client/app/components/shared/time/datepicker/TimeInput.jsx
> +      this.props.onChange();
It is not so obvious what it does. You could replace it with some other method, like: setDefaultTime or something

2016-09-20 10:03 UTC, adamzima commented on app/models/google_calendar/event_wrapper/builder.rb
> +        Google::Apis::CalendarV3::EventDateTime.new(date_time: date_time)
You'll have conflict with recurring PR

2016-09-20 10:03 UTC, adamzima commented on client/app/components/calendar/modal/layout/ModalBody.jsx
> +    onGuestsError: func.isRequired
Why you've changed the name?

2016-09-20 10:04 UTC, adamzima commented on client/app/components/calendar/modal/layout/body/FormDateField.jsx
>        <div className="text-danger">{errors[0]}</div>
Do you want to display empty div anyway?

2016-09-20 10:06 UTC, adamzima commented on client/app/components/calendar/modal/layout/body/FormTextField.jsx
> +      {_.capitalize(name)}:{required ? '*' : ''}
`{required ? '*' : ''}` everywhere. Any idea how to make it more DRY?

2016-09-20 10:06 UTC, adamzima commented on client/app/components/shared/time/datepicker/DateInput.jsx
> +                  className={`date form-control ${this.props.className}`}
weird formatting

2016-09-20 10:07 UTC, adamzima commented on client/app/components/shared/time/datepicker/DateRangePicker.jsx
> +const INITIAL_TIME = roundedTime(moment(), 60 * 30);
magic number `60 * 30`

2016-09-20 10:08 UTC, adamzima commented on client/app/components/shared/time/datepicker/TimeInput.jsx
> +  timeFormat: 'G:i'
<3

2016-09-20 10:09 UTC, adamzima requested changes

2016-09-20 13:31 UTC, quirk0o commented on client/app/components/shared/time/datepicker/TimeInput.jsx
> +             className={`time form-control ${this.props.className}`}
Yes

2016-09-20 13:39 UTC, quirk0o commented on client/app/components/shared/time/datepicker/TimeInput.jsx
> +      this.props.onChange();
How about no?

2016-09-20 14:40 UTC, quirk0o commented on client/app/components/calendar/modal/layout/body/FormTextField.jsx
> +      {_.capitalize(name)}:{required ? '*' : ''}
Done

2016-09-20 14:40 UTC, quirk0o commented on client/app/components/shared/time/datepicker/DateInput.jsx
> +                  className={`date form-control ${this.props.className}`}
Done

2016-09-20 14:41 UTC, quirk0o commented on client/app/components/shared/time/datepicker/TimeInput.jsx
> +      this.props.onChange();
Done

2016-09-20 14:41 UTC, quirk0o commented on app/models/google_calendar/event_wrapper/builder.rb
> +        Google::Apis::CalendarV3::EventDateTime.new(date_time: date_time)
What are we supposed to do about it?

2016-09-20 14:41 UTC, quirk0o commented on client/app/components/calendar/modal/layout/ModalBody.jsx
> +    onGuestsError: func.isRequired
Check again - we now have to error callbacks for date and location

2016-09-20 14:43 UTC, quirk0o commented on client/app/components/calendar/modal/layout/body/FormDateField.jsx
>        <div className="text-danger">{errors[0]}</div>
Done

2016-09-20 14:43 UTC, quirk0o commented on client/app/components/shared/time/datepicker/DateRangePicker.jsx
> +const INITIAL_TIME = roundedTime(moment(), 60 * 30);
Done

2016-09-20 19:15 UTC, adamzima approved these changes

2016-09-21 07:57 UTC, merged