Add month calendar in SideNav
u2i/confy pull request #146
Opened 2016-09-15 14:25 UTC by lkudyba

@quirk0o @mhib @jtkpiotr @adamzima @s1mplex

2016-09-16 13:47 UTC, quirk0o commented on client/app/components/calendar/layout/SideCalendar.jsx
> +    });
This doesn't seem like a good place to put global locale initialization.
Maybe put it in `Register.jsx` ? Or separate config file that you load in `Register.jsx`?

2016-09-16 13:59 UTC, quirk0o commented on client/app/components/calendar/layout/SideCalendar.jsx
> +    this.state = { value: moment() };
You should not store date here - there should be once source of truth about the date being currently displayed in the calendar - the date from the router query.
Inject it into `SideCalendar` as a prop

2016-09-16 14:02 UTC, quirk0o commented on client/test/components/calendar/layout/SideCalendar.spec.jsx
> +  describe('_routeToSelectedDate()', () => {
Don't test private component methods T_T

2016-09-16 14:02 UTC, quirk0o requested changes

2016-09-19 10:12 UTC, s1mplex commented on client/app/components/calendar/layout/SideCalendar.jsx
> +  disableWeekend(date) {
This method doesn't disable weekends. It returns true if the date is a weekday. I'd call it `isWeekday`

2016-09-19 10:13 UTC, madejejej approved these changes

2016-09-20 07:51 UTC, quirk0o commented on client/app/components/calendar/layout/SideCalendar.jsx
> +  onSelect(date) {
Convention is to start handler names with `handle..` ;)

2016-09-20 07:53 UTC, quirk0o commented on client/app/components/calendar/table/Calendar.jsx
> +  selectedDay(day) {
Maybe name is `isSelectedDay`?

2016-09-20 07:54 UTC, quirk0o approved these changes

2016-09-20 07:54 UTC, quirk0o commented on client/test/components/calendar/layout/SideCalendar.spec.jsx
> +  describe('_routeToSelectedDate()', () => {
;(

2016-09-20 08:57 UTC, merged