[Feature] creating ad-hoc events from tablet view
u2i/confy pull request #151
Opened 2016-09-20 10:09 UTC by quirk0o

@adamzima @s1mplex @pbzymek @lkudyba @jtkpiotr @mhib

2016-09-21 11:00 UTC, s1mplex commented on client/app/components/conference_room/provider/EventProvider.jsx
> +  handleConfirm() {
Is there anything bad that can happen when `handleConfirm` / `handleFinish` / `handleCreate` are called multiple times?

2016-09-21 11:01 UTC, madejejej requested changes

2016-09-21 11:01 UTC, madejejej commented on client/app/components/conference_room/layout/controls/Controls.jsx
>    event ?
I'd use if-else instead of the ternary operator here

2016-09-21 11:01 UTC, madejejej commented on client/app/components/conference_room/layout/controls/new_event/AvailableTimeButton.jsx
> +          onClick={() => { if (onClick) onClick(nextEventStart); }}>
I think it'd be better to pass `onClick` which is already aware of the value of `nextEventStart` so we have to pass only one prop instead of two.

2016-09-21 14:34 UTC, quirk0o commented on client/app/components/conference_room/layout/controls/new_event/AvailableTimeButton.jsx
> +          onClick={() => { if (onClick) onClick(nextEventStart); }}>
I did it this way because I wanted the same interface for `AvailableTimeButton` and `TimeChoiceButton`

2016-09-21 14:53 UTC, mhib commented on client/app/components/conference_room/provider/EventProvider.jsx
> +  handleConfirm() {
No.

2016-09-21 15:25 UTC, quirk0o commented on client/app/components/conference_room/layout/controls/Controls.jsx
>    event ?
Done

2016-09-21 15:25 UTC, quirk0o commented on client/app/components/conference_room/layout/controls/new_event/AvailableTimeButton.jsx
> +          onClick={() => { if (onClick) onClick(nextEventStart); }}>
Done

2016-09-22 08:34 UTC, madejejej approved these changes

2016-09-22 08:38 UTC, merged