Updated css for the tablet view - part 1
u2i/confy pull request #165
Opened 2016-09-26 12:13 UTC by jacekkrecioch

2016-09-26 12:31 UTC, jtkpiotr approved these changes
outstanding job Jacek 👍

2016-09-26 12:45 UTC, quirk0o commented
robi wrażenie

2016-10-04 14:38 UTC, adamzima requested changes

2016-10-04 14:38 UTC, adamzima commented on db/seeds.rb
> +  params = { capacity: rand(5..20), color: color, email: mail, kind: kind, logo: logo }
bang, won't work my dear. Where is migration for this field?

2016-11-16 12:37 UTC, adamzima approved these changes

2016-11-18 08:26 UTC, merged